---
title: "tidyr"
author: "Brett Longworth"
date: "10/13/2021"
output: html_document
---

```{r}
library(tidyverse)
library(dplyr)
library(tidyr)
```
```{r}
gapminder <- read.csv("data/gapminder_data.csv")
```

```{r}
gap_wide <- read.csv("data/gapminder_wide.csv")
```

```{r}
str(gap_wide)
```

```{r}
gap_long <- gap_wide %>% 
  pivot_longer(cols = c(starts_with('pop'), starts_with('lifeExp'), starts_with('gdpPercap')),
               names_to = "obstype_year",
               values_to = "obs_values")
```

```{r}
gap_long <- gap_long %>% 
  separate(obstype_year, into = c('obstype', 'year'), sep = "_")
  
```

```{r}
gap_normal <- gap_long %>% 
  pivot_wider(names_from = obstype,
              values_from = obs_values)
```

```{r}
names(gapminder)
```

```{r}
names(gap_normal)
```

```{r}
gap_normal <- gap_normal[, names(gapminder)]

gap_normal <- gap_normal %>% 
  mutate(year = as.integer(year))
```


```{r}
str(gap_no)
all_equal(gap_normal, gapminder)

```
```{r}
str(gap_normal)
```
```{r}
str(gapminder)
```
```{r}
class(gapminder)
```

```{r}
class(gap_normal)
```

